voting/election/urls.py
from django.conf.urls import url
from .views import ElectionList, CreateElection, MainPage, ElectionDetail, ThanksPage, Results
from django.contrib import admin


urlpatterns = [
   url(r'^election/$', ElectionList.as_view(), name='election-name'),
   url(r'^create-election/$', CreateElection.as_view(), name='create-election'),
   url(r'^home/', MainPage.as_view(), name='main_page'),  #Home page for loged in student
   url(r'^election/(?P<pk>\d+)$', ElectionDetail.as_view(), name='election-detail'),
   url(r'^success/$', ThanksPage.as_view(), name='success-vote'),
   url(r'^results/', Results.as_view(), name='results')
]

voting/voting/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('election.urls', namespace='election')),
    url(r'^accounts/', include('django.contrib.auth.urls'))
]
#Add Django site authentication urls (for login, logout, password management)
#urlpatterns += [
  #  url(r'^accounts/', include('django.contrib.auth.urls')),
#]

voting/election/models.py
from django.db import models
from user.models import User
from user.models import Group
# Create your models here.


class Election(models.Model):

    STATUS_CHOICES =(
        (0, 'Open'),
        (1, 'Close'),
        (2, 'Canceled'),
        (3, 'Disqualified ')
    )
    name = models.CharField(max_length=255) #default 5
    description = models.TextField(max_length=512) #default 1?

    startDate = models.DateTimeField()
    endDate = models.DateTimeField()
    status = models.IntegerField(choices=STATUS_CHOICES)
    group = models.ForeignKey(Group)
    #include the ballot and the election choices

class ElectionChoices(models.Model):

    election = models.ForeignKey(Election)  # specify model
    optionName = models.CharField(max_length=255)
    votes = models.IntegerField(default=0) #used to count the votes for a certain option


class Vote(models.Model):
   user = models.ForeignKey(User) # - do we really need that?
   electionChoice = models.ForeignKey(ElectionChoices)
   election = models.ForeignKey(Election)

voting/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class Group(models.Model):

    name = models.CharField(max_length=255)

    def __str__(self):
        return '%s - %s' % (self.id, self.name)


class User(AbstractUser):

    GENDER_CHOICES = (
        (0, ('Male')),
        (1, ('Female')),
    )

    ROLE_CHOICES = (
        (0, ('Student')),
        (1, ('Proffesor')),
        (2, ('Administration')),
        (3, ('ElectionComisioner'))

    )

    gender = models.IntegerField(choices=GENDER_CHOICES, default=0)
    role = models.IntegerField(choices=ROLE_CHOICES, default=2)
    groups = models.ManyToManyField(Group)

voting/election/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import Election, ElectionChoices


class ElectionForm(forms.ModelForm):

    class Meta:
        model = Election
        exclude = ()

# asta cumva trebuie de inclus pe pagina Create Election
# Adaugam optiunile de vot, 2 sau mai multe
# optionName from ElectionChoices

class ChoiceForm(forms.ModelForm):

    class Meta:
        model = ElectionChoices
        exclude = ()

ChoiceFormSet = inlineformset_factory(Election, ElectionChoices, form=ChoiceForm, extra=1)

voting/election/views.py
from django.db import transaction
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.shortcuts import reverse
from django.forms.formsets import formset_factory
from django.template import RequestContext
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

from .forms import ElectionForm, ChoiceForm, ChoiceFormSet
from .models import Election, ElectionChoices, Vote
from django.views import View

# Create your views here.


class MainPage(View):

    def get(self, request):
        return render(request, 'main.html')


class ThanksPage(View):

    def get(self, request):
        return render(request, 'success.html')

    def post(self, request):
        pass


class ElectionList(LoginRequiredMixin, View): #page of election

    def get(self, request):
        elections = Election.objects.filter(status=0)
        return render(request, 'home.html', {'elections': elections})

    def post(self, request):
        pass


class ElectionDetail(LoginRequiredMixin, View):
    def get(self, request, pk):
        election_id = Election.objects.get(pk=pk)
        return render(request, 'election/election_detail.html', {'election':election_id})

    def post(self, request):

        if request.POST:
            return redirect('/success/')
        else:
            return redirect('/success/')
    '''
    def vote(self, request, pk):
        e = get_object_or_404(Election, pk=pk)
        try:
            selected_choice = e.electionchoices_set.get(pk=request.POST['choice'])
        except (KeyError, ElectionChoices.DoesNotExist):
            # Redisplay the poll voting form.

            return render_to_response('election/election_detail.html', {
                'election': e,
                'error_message': "You didn't select a choice.",
            }, context_instance=RequestContext(request))
        else:
            selected_choice.votes += 1
            selected_choice.save()
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
            return HttpResponseRedirect(reverse('results/', args=(e.id,)))
        '''


class CreateElection(LoginRequiredMixin, CreateView): # creating a new election only by administration and EC
    def get(self,request):
        return redirect('/admin/election/election/add/')
    '''
    model = Election
    fields = ['name', 'description', 'startDate', 'endDate', 'status', 'group']
    success_url = reverse_lazy('election:election-name')

    def get_context_data(self, **kwargs):
        data = super(CreateElection,self).get_context_data(**kwargs)
        if self.request.POST:
            data['electionchoices'] = ChoiceFormSet(self.request.POST)
        else:
            data['electionchoices'] = ChoiceFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        electionchoices = context['electionchoices']
        with transaction.atomic():
            self.object = form.save()

            if electionchoices.is_valid():
                electionchoices.instance = self.object
                electionchoices.save()
        return super(CreateElection, self).form_valid(form)
        '''

class Results(View):

    def get(self, request):
        return render(request, 'election/results.html')

voting/user/views.py
from django.shortcuts import render
from election.models import Election
from django.views import View
# Create your views here.


def home(request):
    if request.method == 'GET':
        elections = Election.objects.filter(status=0)
        return render(request, 'templates/home.html', {'election': elections})
    if request.method == 'POST':
        pass





    # creaza functii + logica + return la HTTPResponse
    #creare utilizator
    #logarea

voting/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>


    </style>
<script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous">


</script>
</head>
<body >
    {% block navigation_menu %}
        {% include 'partials/navigation_menu.html' %}
    {% endblock %}

    {% block content %}
        
    {% endblock %}

    {% block footer %}
        <footer>
    <div class="container">
        <hr />
        <p class="text-center">Copyright © Ana-Maria's APPOO course work project 2017.</p>
    </div>
</footer>
    {% endblock %}


</body>



</html>

voting/templates/election/election_detail.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <br>
    <br>
  <h1>Election: {{ election.name }}</h1>
    <br>

    <div class="well">

    <form role="form" class="clearfix">

        <div class="col-md-12 form-group">
            <label>   Description:</label>
        {{ election.description }}
        </div>

        <div class="col-md-12 form-group">
        <label >Start Date:</label>
        {{ election.startDate }}
    </div>
    <div class="col-md-12 form-group">
        <label >End Date:</label>
        {{ election.endDate }}
    </div>

    <div class="col-md-12 form-group text-left"><label>Choose an option:</label></div>
    <div class="col-md-12 form-group text-left">
        <!-- The option should be included and Vote button-->

        <form action="{% url 'election:success-vote' %}" method="post">
    {% csrf_token %}
    {% for electionchoices in election.electionchoices_set.all %}


    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choices.id }}" />
        <label for="choices{{ forloop.counter }}">{{ electionchoices.optionName }}</label><br />

    {% endfor %}

            <input type="submit" value="Vote" class="btn btn-danger" />
        </form>

    </div>
    </form>
    </div>

{% endblock %}

voting/templates/election/election_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



    <div class="col-md-8">
        <h1>Election</h1>
        <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <table class="table">

            {{ electionchoices.management_form }}

            {% for form in electionchoices.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th>{{ field.label|capfirst }}</th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}

            <tr class="{% cycle row1 row2 %} formset_row">
                        {% for field in form.visible_fields %}
                            <td>
                                {# Include the hidden fields in the form #}
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {{ field }}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>

        <input type="submit" value="Save"/> <a href="{% url 'election:election-name' %}">back to the elections page</a>
        </form>
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="{% static 'formset/jquery.formset.js' %}"></script>
    <script type="text/javascript">
        $('.formset_row').formset({
            addText: 'add option',
            deleteText: 'remove',
            prefix: 'electionchoice_set'
        });
    </script>


{% endblock %}

voting/templates/election/results.html
{% extends 'base.html' %}



<script>

</script>
<style>


</style>
{% block content %}

<div class="well">
<br>
    <br>
<br>

    <dl>
  <dt>
    Some dummy data for results:
  </dt>
        <br>
  <dd class="percentage percentage-11"><span class="text">IE 11: 11.33%</span></dd>
  <dd class="percentage percentage-49"><span class="text">Chrome: 49.77%</span></dd>
  <dd class="percentage percentage-16"><span class="text">Firefox: 16.09%</span></dd>
  <dd class="percentage percentage-5"><span class="text">Safari: 5.41%</span></dd>
  <dd class="percentage percentage-2"><span class="text">Opera: 1.62%</span></dd>
  <dd class="percentage percentage-2"><span class="text">Android 4.4: 2%</span></dd>
</dl>
</div>
{% endblock %}
    <!-- This code makes a paragraph
<ul>
{% for choice in election.electionchoices_set.all %}
    <li>{{ choice.choice }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>


-->

voting/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
<script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>
</head>
<body>

    {% block navigation_menu %}
        {% include 'partials/navigation_menu.html' %}
    {% endblock %}


    <br>
    <br>
    <br>
    <div>
    <h1>List of elections</h1>
    <article>

    {% for election in elections %}

            <h2><a href="{% url 'election:election-detail' election.id %}">{{ election.name }}</a>  </h2>

            <div class="group1 col-sm-6 col-md-6">
                <span class="glyphicon glyphicon-eye-open"></span>  Status: {{ election.get_status_display }}
            </div>
        <div class="group2 col-sm-6 col-md-6">
                <span class="glyphicon glyphicon-time"></span>  End Date: {{ election.endDate  }}
        </div>
        <hr>
    <br />
        <p class="lead">{{ election.description }} </p>

    {% endfor %}

{% block footer %}
<footer>
    <div class="container">
        <hr />
        <p class="text-center">Copyright © Ana-Maria's APPOO course work project 2017</p>
    </div>
</footer>
    {% endblock %}
</body>
</html>

voting/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
    <script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>
</head>
<body>
    {% block navigation_menu %}
        {% include 'partials/navigation_menu.html' %}
    {% endblock %}

<div class="container">
  <div class="jumbotron">
    <h1>Voting System</h1>
    <p> University online voting system. Allowing students and professors to vote from virtually anywhere.
        Go to election pages and choose the specific election to vote. </p>
  </div>

</div>

</body>
</html>

voting/templates/partials/navigation_menu.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}


<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/home" class="navbar-brand">eVoting</a>
        </div>
        <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">


<ul class="nav navbar-nav">
    {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
   {% else %}
     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
   {% endif %}

    <li>
        <a href="{% url 'election:election-name' %}">Elections</a>
    </li>
    <li>
        <a href="{% url 'election:results' %}">Results</a>
    </li>
    {% if user.role == 2 %}
    <li>
        <a href="{% url 'election:create-election' %}">Create Election</a>
    </li> {% endif %}

</ul>
        </nav>
    </div>
</header>

voting/templates/success.html
{% extends 'base.html' %}

{% block content %}


    <div class="container text-center" >
  <div class="jumbotron">
    <h2>Thank you for your vote!</h2>
    <p>Your vote was registered successfully! </p>
      <br>
    <a href="{% url 'election:election-name'  %}">Back to elections</a>
  </div>

</div>

{% endblock %}